# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/trust/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-11612-DESKTOP-OFLNA5L/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xa7a15tcpg236-1Q

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/micro_projects/project_5/project_5.cache/wt [current_project]
set_property parent.project_path D:/micro_projects/project_5/project_5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/micro_projects/project_5/project_5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/ALU.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/Address_Regester.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/BUS.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/Data_Regester.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/Instruction_Regester.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/Memory.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/Seqence_counter.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/Timer.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/operation_selecction.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/processor_reg.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/program_counter.v
  D:/micro_projects/project_5/project_5.srcs/sources_1/new/mano.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top mano -part xa7a15tcpg236-1Q


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mano.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mano_utilization_synth.rpt -pb mano_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
